### ISSUE TITLE
[1.16.4]server crash

### ISSUE THREAD

**Issue by zyjjustplay** [kwpugh/MoreGems#37]
[09:19:51] [main/INFO]: Compression will use Java 11, encryption will use Java
[09:19:51] [main/INFO]: Tom's Storage Setup starting
[09:19:51] [main/INFO]: Loaded 14 Static Content files for vanilla-hammers:hammers
[09:19:51] [main/INFO]: Definitely not up to no good
[09:19:51] [main/INFO]: Beginning initialization...
[09:19:51] [main/INFO]: Finished initialization!
[09:19:51] [main/INFO]: [STDOUT]: Hello CPP world!
[09:19:51] [main/INFO]: Loaded 5 Static Content files for wolveswitharmor:wolf_armor
[09:19:53] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'more_gems'!
        at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.9) ~[?:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main:92) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: top/theillusivec4/curios/api/SlotTypeInfo$BuildScheme
        at com.kwpugh.more_gems.MoreGems.onInitialize(MoreGems.java:41) ~[MoreGems-Fabric_1.16.5-1.1.25_2.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: top.theillusivec4.curios.api.SlotTypeInfo$BuildScheme
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at com.kwpugh.more_gems.MoreGems.onInitialize(MoreGems.java:41) ~[MoreGems-Fabric_1.16.5-1.1.25_2.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more

**Comment by kwpugh** [comment]
use 1.16.5.   1.16.4 is no longer supported.

**Comment by kwpugh** [comment]
and it looks like you are missing Curios
